<?php

define("PAGE_TYPE_ADMIN_ONLY", "ADMIN");
define("PAGE_TYPE_REGISTERED_ONLY","REGISTERED");
define("PAGE_TYPE_LOGGED_IN_ONLY", "LOGGEDIN");
define("PAGE_TYPE_ANON_ONLY", "ANONONLY");
define("PAGE_TYPE_ALL", "ANON");
define("REGISTERED_USER_TYPE", "REGISTERED");
define("UNREGISTERED_USER_TYPE", "ANON");
define("ADMIN_USER_TYPE", "ADMIN");

